services:
  postgres:
    container_name: fib-postgres-dev
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    container_name: fib-redis-dev
    image: 'redis:latest'
    restart: always

  nginx:
    container_name: fib-nginx-dev
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'

  api:
    container_name: fib-api-dev
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    restart: on-failure
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}

  client:
    container_name: fib-client-dev
    environment:
      - WDS_SOCKET_PORT=0
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    restart: on-failure

  worker:
    container_name: fib-worker-dev
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    restart: on-failure
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
